service: "service"

provider:
  name: "aws"
  stage: "dev"
  region: "eu-north-1"
  runtime: "nodejs18.x"
  memorySize: "512"
  logRetentionInDays: "7"
  architecture: "arm64"
  environment:
    POWERTOOLS_DEV: true

functions:
  hello:
    handler: "function.handler"
    events:
      - httpApi: "GET /"
