service: "calculator"

provider:
  name: "aws"
  stage: "dev"
  region: "eu-north-1"
  runtime: "nodejs18.x"
  memorySize: "512"
  logRetentionInDays: "7"
  architecture: "arm64"

functions:
  hello:
    handler: "functions/sum/handler"
    events:
      - httpApi: "POST /"

plugins:
  - "serverless-plugin-typescript"
