service: "calculator"
frameworkVersion: "=3.36.0"

provider:
  name: "aws"
  stage: "dev"
  region: "eu-north-1"
  runtime: "nodejs18.x"
  memorySize: "512"
  logRetentionInDays: "7"
  architecture: "arm64"

functions:
  sum:
    handler: "functions/sum/handler.default"
    events:
      - httpApi: "POST /"

plugins:
  - "serverless-esbuild"
