service: "calculator"
frameworkVersion: "=3.36.0"

provider:
  name: "aws"
  stage: "dev"
  region: "eu-north-1"
  runtime: "nodejs18.x"
  memorySize: "512"
  logRetentionInDays: "7"
  architecture: "arm64"

  httpApi:
    cors:
      allowedOrigins:
        - "http://localhost:5173"
        - "https://seed-2yj.pages.dev"
      allowedMethods:
        - "POST"

functions:
  sum:
    handler: "functions/sum/handler.default"
    events:
      - httpApi:
          path: "/sum"
          method: "POST"

plugins:
  - "serverless-esbuild"
